on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

name: Code linting

env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features