on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with: 
        submodules: recursive
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test -- --color always --nocapture
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test -- --color always --nocapture
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test -- --color always --nocapture
  freebsd:
    runs-on: ubuntu-latest # Ubuntu w/ FreeBSD-vm from vmactions 
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build and run tests
        id: freebsd
        uses: vmactions/freebsd-vm@v1
        with:
           prepare : |
             pkg install -y rust llvm
           run : |
             cargo build --verbose
             cargo test -- --color always --nocapture
